server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: change-this-to-a-very-long-random-secret-change-me-1234567890abcd
  expiration-ms: 86400000
