server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-shy-dream-a1cm704u-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_uMdCyfnI74aG}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:change-this-to-a-very-long-random-secret-change-me-1234567890abcd}
  expiration-ms: ${JWT_EXPIRATION:86400000}